#!/usr/bin/env bash
# Rofi launcher. Place launcher in rofi/bin.

rofi \
	-show drun \
	-drun-display-format "{name}" \
	-kb-cancel Escape \
	-theme "$HOME"/.config/rofi/config/themes/tokyonight.rasi
