#!/usr/bin/env bash
# Rofi launcher. Place launcher in rofi/bin.

rofi \
	-show drun \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
        -kb-cancel Escape \
	-theme "$HOME"/.config/rofi/config/dec26/rofi-dock-2.rasi
